#!/usr/bin/env ruby
# frozen_string_literal: true

require 'erb'
require 'octokit'

Octokit.configure do |c|
  c.auto_paginate = true
end

Octokit::Client.new(
  access_token: ENV['GITHUB_TOKEN']
).tap do |client|
  @repos = client.org_repos('kleister').sort_by(&:name).select do |row|
    row.name.start_with? 'kleister-' or row.name.end_with? '-kleister'
  end.map do |row|
    workflows = client.contents(row.full_name, path: '.github/workflows', query: { ref: 'master' }).map do |w|
      w.name.delete_suffix('.yml')
    end

    {
      name: row.name,
      workflows:
    }
  rescue StandardError
    nil
  end.compact

  File.write(
    File.expand_path(
      '../STATUS.md',
      __dir__
    ),
    ERB.new(
      File.read(
        File.expand_path(
          '../templates/status.erb',
          __dir__
        )
      ),
      trim_mode: '-'
    ).result
  )
end
